name: Update Tracker

on:
  issues: { types: [opened, edited, labeled] }
  issue_comment: { types: [created, edited] }
  # OPTIONAL: periodic refresh every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # OPTIONAL: manual run with an optional issue number
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to update (optional)"
        required: false

permissions:
  issues: write

jobs:
  check-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Only Octokit needed. Node 20 has global fetch.
      - run: npm install @octokit/rest dayjs

      - name: Run tracker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ inputs.issue_number || github.event.issue.number }}
          EVENT_NAME: ${{ github.event_name }}
          COMMENT_BODY: ${{ github.event_name == 'issue_comment' && github.event.comment.body || '' }}
          ISSUE_TITLE: ${{ github.event.issue.title || '' }}
        run: node .github/scripts/update-tracker.js
